/*
 * Телеграм Бот для работы с научными группами
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/api/v1/",
		Index,
	},

	Route{
		"FindTutorByScientificInterest",
		strings.ToUpper("Get"),
		"/api/v1/FindTutorByScientificInterest/{scientific_interest}",
		FindTutorByScientificInterest,
	},

	Route{
		"FindTutorHasFreePlaces",
		strings.ToUpper("Get"),
		"/api/v1/FindTutorHasFreePlaces",
		FindTutorHasFreePlaces,
	},

	Route{
		"SignInUser",
		strings.ToUpper("Post"),
		"/api/v1/user/signIn",
		SignInUser,
	},

	Route{
		"SignUpUser",
		strings.ToUpper("Post"),
		"/api/v1/user/signUp",
		SignUpUser,
	},
}
